import { describe, expect, it } from "vitest"
import { existsSync, readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

import { runWithLoading } from "../utils/async-state"

describe("runWithLoading", () => {
  it("clears loading after resolve", async () => {
    const states: boolean[] = []
    await expect(runWithLoading((value) => states.push(value), async () => "ok")).resolves.toBe("ok")
    expect(states).toEqual([true, false])
  })

  it("clears loading after rejection", async () => {
    const states: boolean[] = []
    await expect(runWithLoading((value) => states.push(value), async () => { throw new Error("offline") }))
      .rejects.toThrow("offline")
    expect(states).toEqual([true, false])
  })

  it("clears loading after an abort-shaped rejection", async () => {
    const states: boolean[] = []
    await expect(runWithLoading((value) => states.push(value), async () => {
      throw new DOMException("The operation was aborted", "AbortError")
    })).rejects.toMatchObject({ name: "AbortError" })
    expect(states).toEqual([true, false])
  })

  it("keeps existing H5 async controls disabled while pending", () => {
    const assessment = readFileSync(new URL("../pages/career-assessment/index.vue", import.meta.url), "utf8")
    const applications = readFileSync(new URL("../pages/applications/index.vue", import.meta.url), "utf8")
    const planner = readFileSync(new URL("../pages/career-planner/index.vue", import.meta.url), "utf8")
    const membership = readFileSync(new URL("../pages/membership/index.vue", import.meta.url), "utf8")
    const privacy = readFileSync(new URL("../pages/privacy/index.vue", import.meta.url), "utf8")
    const editor = readFileSync(new URL("../pages/resume-editor/index.vue", import.meta.url), "utf8")
    const jobSearch = readFileSync(new URL("../pages/job-search/index.vue", import.meta.url), "utf8")
    const jobCollection = readFileSync(new URL("../pages/job-collection/index.vue", import.meta.url), "utf8")
    const operatorKnowledge = readFileSync(new URL("../pages/operator-knowledge/index.vue", import.meta.url), "utf8")
    expect(assessment).toContain(':loading="submitting" :disabled="submitting"')
    expect(assessment).toContain("<LoadingSpinner")
    expect(applications).toContain("const timelineSaving = ref(false)")
    expect(applications).toContain("const reminderSaving = ref(false)")
    expect(applications).toContain("const pendingDeleteId = ref(\"\")")
    expect(applications).toContain(':loading="timelineSaving" :disabled="timelineSaving"')
    expect(applications).toContain(':loading="reminderSaving" :disabled="reminderSaving"')
    expect(planner).toContain(':loading="taskSaving" :disabled="taskSaving"')
    expect(planner).toContain(':loading="loading" :disabled="loading"')
    expect(membership).toContain(':loading="purchasing" :disabled="purchasing"')
    expect(membership).toContain("<LoadingSpinner")
    expect(privacy).toContain(':loading="backupBusy" :disabled="backupBusy"')
    expect(editor).toContain(':loading="importLoading" :disabled="importLoading || saveLoading || versionLoading || Boolean(versionComparingId || restoringVersionId || exporting)"')
    expect(editor).toContain(':loading="versionLoading" :disabled="versionLoading || Boolean(versionComparingId || restoringVersionId || importLoading || exporting)"')
    expect(jobSearch).toContain(':loading="marketSearchLoading" :disabled="marketSearchLoading"')
    expect(jobSearch).toContain(':loading="reviewLoading" :disabled="reviewLoading || pdfLoading"')
    expect(jobSearch).toContain(':loading="adviceLoading" :disabled="adviceLoading"')
    expect(jobCollection).toContain(':loading="saving" :disabled="saving"')
    expect(operatorKnowledge).toContain('const versionsLoading = ref("")')
    expect(operatorKnowledge).toContain("<LoadingSpinner")
    expect(operatorKnowledge).toContain(':loading="loading" :disabled="loading || Boolean(versionsLoading) || restoringVersion !== null"')
    expect(operatorKnowledge).toContain(':loading="versionsLoading === item.id"')
    expect(operatorKnowledge).toContain(':loading="restoringVersion === version.version"')
    expect(applications).toContain("if (saving.value) return")
    expect(assessment).toContain("if (submitting.value) return")
    expect(jobSearch).toContain("if (loading.value) return")
    expect(jobSearch).toContain("if (marketSearchLoading.value || !activeRoleName.value) return")
    expect(jobSearch).toContain("if (reviewLoading.value || pdfLoading.value) return")
    expect(jobSearch).toContain("if (adviceLoading.value) return")
    expect(membership).toContain("if (purchasing.value) return")
  })

  it("locks cross-action login and resume version requests while pending", () => {
    const login = readFileSync(new URL("../pages/login/index.vue", import.meta.url), "utf8")
    const editor = readFileSync(new URL("../pages/resume-editor/index.vue", import.meta.url), "utf8")
    const collection = readFileSync(new URL("../pages/job-collection/index.vue", import.meta.url), "utf8")
    expect(login).toContain(':loading="sending" :disabled="sending || loggingIn"')
    expect(login).toContain(':loading="loggingIn" :disabled="loggingIn || sending"')
    expect(login).toContain(':disabled="passwordAction !== null || sending || loggingIn"')
    expect(editor).toContain('const versionComparingId = ref("")')
    expect(editor).toContain(':loading="versionComparingId === version.id"')
    expect(editor).toContain(':loading="restoringVersionId === version.id"')
    expect(editor).toContain('if (exporting.value || saveLoading.value || importLoading.value || versionLoading.value || versionComparingId.value || restoringVersionId.value) return')
    expect(collection).toContain("if (removingFavoriteId.value || subscriptionSaving.value) return")
  })

  it("centralizes H5 error and disabled-state presentation", () => {
    const app = readFileSync(new URL("../App.vue", import.meta.url), "utf8")
    const login = readFileSync(new URL("../pages/login/index.vue", import.meta.url), "utf8")
    const applications = readFileSync(new URL("../pages/applications/index.vue", import.meta.url), "utf8")
    expect(app).toContain("--ui-error-bg")
    expect(app).toContain("button:disabled")
    expect(app).toContain("background-color: var(--ui-disabled-bg) !important")
    expect(app).toContain(".ui-error-tip")
    expect(login).toContain("ui-error-tip")
    expect(applications).toContain("ui-error-tip")
  })

  it("contains off-screen H5 long-list items without changing list data", () => {
    const app = readFileSync(new URL("../App.vue", import.meta.url), "utf8")
    const applications = readFileSync(new URL("../pages/applications/index.vue", import.meta.url), "utf8")
    const evidence = readFileSync(new URL("../pages/evidence/index.vue", import.meta.url), "utf8")
    const jobs = readFileSync(new URL("../pages/job-search/index.vue", import.meta.url), "utf8")
    expect(app).toContain(".ui-long-list-item")
    expect(app).toContain("content-visibility: auto")
    expect(app).toContain("contain-intrinsic-size")
    expect(applications).toContain("ui-long-list-item")
    expect(evidence).toContain("ui-long-list-item")
    expect(jobs).toContain("ui-long-list-item")
  })

  it("exposes H5 form, action, and overlay accessibility semantics", () => {
    const field = readFileSync(new URL("../components/FormField.vue", import.meta.url), "utf8")
    const onboarding = readFileSync(new URL("../components/OnboardingTour.vue", import.meta.url), "utf8")
    const jobs = readFileSync(new URL("../pages/job-search/index.vue", import.meta.url), "utf8")
    const applications = readFileSync(new URL("../pages/applications/index.vue", import.meta.url), "utf8")

    expect(field).toContain(':aria-label="label"')
    expect(field).toContain(':aria-invalid="Boolean(error)"')
    expect(field).toContain(':aria-describedby="error ? errorId : undefined"')
    expect(field).toContain("getCurrentInstance")
    expect(field).not.toContain("useId")
    expect(onboarding).toContain('@tap="closeFromMask"')
    expect(onboarding).toContain("@tap.stop")
    expect(jobs).toContain('role="button"')
    expect(jobs).toContain('tabindex="0"')
    expect(jobs).toContain(':aria-expanded="isAnalysisSectionOpen(section.order)"')
    expect(applications).toContain(':aria-label="`删除 ${item.company} 的 ${item.roleName} 投递记录`"')
  })

  it("uses the accessible H5 long-text contract", () => {
    const componentUrl = new URL("../components/ExpandableText.vue", import.meta.url)
    expect(existsSync(fileURLToPath(componentUrl))).toBe(true)
    const component = readFileSync(componentUrl, "utf8")
    const applications = readFileSync(new URL("../pages/applications/index.vue", import.meta.url), "utf8")
    const collection = readFileSync(new URL("../pages/job-collection/index.vue", import.meta.url), "utf8")
    const jobs = readFileSync(new URL("../pages/job-search/index.vue", import.meta.url), "utf8")
    const preview = readFileSync(new URL("../components/ResumePreview.vue", import.meta.url), "utf8")
    expect(component).toContain(':aria-expanded="expanded"')
    expect(component).toContain("getCurrentInstance")
    expect(component).not.toContain("useId")
    expect(component).toContain("watch(() => props.text")
    expect(component).toContain("-webkit-line-clamp")
    expect(component).toContain("overflow-wrap: anywhere")
    expect(component).toContain("展开")
    expect(component).toContain("收起")
    expect(applications).toContain('<ExpandableText class="record-role"')
    expect(collection).toContain('<ExpandableText class="role"')
    expect(jobs).toContain('<ExpandableText class="role"')
    expect(preview).toContain(':expand-at="96"')
  })
})
