"""Create the portable Phase 8 baseline schema.

Revision ID: 20260819_phase8
Revises:
Create Date: 2026-08-19
"""

from __future__ import annotations

from alembic import op


revision = "20260819_phase8"
down_revision = None
branch_labels = None
depends_on = None


def _identity_column() -> str:
    if op.get_context().dialect.name == "postgresql":
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def upgrade() -> None:
    statements = (
        "CREATE TABLE IF NOT EXISTS users (user_id TEXT PRIMARY KEY, phone TEXT NOT NULL UNIQUE, token_version INTEGER NOT NULL DEFAULT 1 CHECK (token_version >= 1), created_at TEXT NOT NULL, last_login TEXT NOT NULL, is_deleted BOOLEAN NOT NULL DEFAULT FALSE, deleted_at TEXT, privacy_consent_at TEXT)",
        "CREATE TABLE IF NOT EXISTS user_draft (id TEXT PRIMARY KEY, client_id TEXT NOT NULL, user_id TEXT REFERENCES users(user_id), job_title TEXT NOT NULL, template_id TEXT NOT NULL, payload_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS resume_evidence (id TEXT PRIMARY KEY, client_id TEXT NOT NULL, user_id TEXT REFERENCES users(user_id), kind TEXT NOT NULL, title TEXT NOT NULL, context TEXT NOT NULL, actions TEXT NOT NULL, outcome TEXT NOT NULL, proof_note TEXT NOT NULL, verified BOOLEAN NOT NULL DEFAULT FALSE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS application_tracker (id TEXT PRIMARY KEY, client_id TEXT NOT NULL, user_id TEXT REFERENCES users(user_id), company TEXT NOT NULL, role_name TEXT NOT NULL, city TEXT NOT NULL, source TEXT NOT NULL, status TEXT NOT NULL, applied_at TEXT, next_action_at TEXT, interview_notes TEXT NOT NULL, draft_id TEXT, notes TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS template_table (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL, config_json TEXT NOT NULL, docx_template_path TEXT, active BOOLEAN NOT NULL DEFAULT TRUE)",
        "CREATE TABLE IF NOT EXISTS job_cache (normalized_role TEXT NOT NULL, provider_mode TEXT NOT NULL, payload_json TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY (normalized_role, provider_mode))",
        "CREATE TABLE IF NOT EXISTS download_file (token TEXT PRIMARY KEY, user_id TEXT REFERENCES users(user_id), file_path TEXT NOT NULL, filename TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS user_vip (user_id TEXT PRIMARY KEY REFERENCES users(user_id), vip_level TEXT NOT NULL DEFAULT 'free' CHECK (vip_level IN ('free', 'basic', 'premium')), expire_time TEXT, auto_renew BOOLEAN NOT NULL DEFAULT FALSE, create_time TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS order_record (order_id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(user_id), package_type TEXT NOT NULL CHECK (package_type IN ('monthly', 'quarterly', 'annual')), total_amount INTEGER NOT NULL CHECK (total_amount >= 0), payment_status TEXT NOT NULL CHECK (payment_status IN ('pending', 'paid', 'closed', 'expired')), create_time TEXT NOT NULL, payment_channel TEXT, provider_transaction_id TEXT, entitlement_expire_time TEXT, auto_renew BOOLEAN NOT NULL DEFAULT FALSE)",
        "CREATE TABLE IF NOT EXISTS job_favorite (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(user_id), role_name TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, UNIQUE (user_id, role_name))",
        "CREATE TABLE IF NOT EXISTS job_match_subscription (user_id TEXT PRIMARY KEY REFERENCES users(user_id), enabled BOOLEAN NOT NULL DEFAULT FALSE, match_filter TEXT NOT NULL DEFAULT '', last_notify_at TEXT, updated_at TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS job_catalog (role_name TEXT PRIMARY KEY, category TEXT NOT NULL, aliases_json TEXT NOT NULL, sort_order INTEGER NOT NULL)",
        "CREATE TABLE IF NOT EXISTS role_profile (role_name TEXT PRIMARY KEY, family TEXT NOT NULL, aliases_json TEXT NOT NULL, recommended_majors_json TEXT NOT NULL, adjacent_majors_json TEXT NOT NULL, relevant_courses_json TEXT NOT NULL, required_skills_json TEXT NOT NULL, entry_skills_json TEXT NOT NULL, alternative_roles_json TEXT NOT NULL, internship_roles_json TEXT NOT NULL, entry_difficulty INTEGER NOT NULL CHECK (entry_difficulty BETWEEN 1 AND 5), industry_tags_json TEXT NOT NULL, description TEXT NOT NULL, catalog_origin TEXT NOT NULL DEFAULT 'seed', source_key TEXT, source_version TEXT, source_url TEXT, updated_at TEXT)",
        "CREATE TABLE IF NOT EXISTS major_catalog (major_name TEXT PRIMARY KEY, category TEXT NOT NULL, aliases_json TEXT NOT NULL, related_families_json TEXT NOT NULL, transferable_skills_json TEXT NOT NULL, catalog_origin TEXT NOT NULL DEFAULT 'seed', source_key TEXT, source_version TEXT, source_url TEXT, updated_at TEXT)",
        "CREATE TABLE IF NOT EXISTS career_profile (client_id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(user_id), identity_code TEXT NOT NULL, major TEXT NOT NULL, education_level TEXT NOT NULL, graduation_year INTEGER, city_preferences_json TEXT NOT NULL, minimum_salary TEXT, industry_preferences_json TEXT NOT NULL, work_types_json TEXT NOT NULL, skills_json TEXT NOT NULL, draft_id TEXT, updated_at TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS career_assessment (client_id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(user_id), assessment_version INTEGER NOT NULL, answers_json TEXT NOT NULL, result_json TEXT NOT NULL, updated_at TEXT NOT NULL)",
        f"CREATE TABLE IF NOT EXISTS annual_employment_insight (id {_identity_column()}, year INTEGER NOT NULL, scope TEXT NOT NULL, audience TEXT NOT NULL, category TEXT NOT NULL, title TEXT NOT NULL, content TEXT NOT NULL, source_label TEXT NOT NULL, publication_date TEXT NOT NULL, confidence_note TEXT NOT NULL, created_at TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS official_dataset_source (source_key TEXT PRIMARY KEY, display_name TEXT NOT NULL, direct_url TEXT, allowed_hosts_json TEXT NOT NULL DEFAULT '[]', file_format TEXT NOT NULL, parser_kind TEXT NOT NULL, enabled BOOLEAN NOT NULL DEFAULT FALSE, disabled_reason TEXT, last_version TEXT, last_checksum TEXT, last_synced_at TEXT)",
        f"CREATE TABLE IF NOT EXISTS knowledge_sync_run (id {_identity_column()}, mode TEXT NOT NULL, status TEXT NOT NULL, started_at TEXT NOT NULL, completed_at TEXT, added_roles INTEGER NOT NULL DEFAULT 0, added_majors INTEGER NOT NULL DEFAULT 0, skipped_rows INTEGER NOT NULL DEFAULT 0, errors_json TEXT NOT NULL DEFAULT '[]')",
        "CREATE INDEX IF NOT EXISTS idx_user_draft_owner_updated ON user_draft (user_id, updated_at DESC, id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_resume_evidence_client_updated ON resume_evidence (client_id, updated_at DESC, id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_resume_evidence_owner_updated ON resume_evidence (user_id, updated_at DESC, id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_application_tracker_client_status ON application_tracker (client_id, status, next_action_at, updated_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_application_tracker_owner_status ON application_tracker (user_id, status, next_action_at, updated_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_download_file_owner ON download_file (user_id)",
        "CREATE INDEX IF NOT EXISTS idx_order_record_owner_created ON order_record (user_id, create_time DESC, order_id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_job_favorite_owner_created ON job_favorite (user_id, created_at DESC, id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_career_profile_owner ON career_profile (user_id)",
        "CREATE INDEX IF NOT EXISTS idx_career_assessment_owner ON career_assessment (user_id)",
    )
    for statement in statements:
        op.execute(statement)


def downgrade() -> None:
    for table in (
        "knowledge_sync_run", "official_dataset_source", "annual_employment_insight",
        "career_assessment", "career_profile", "major_catalog", "role_profile",
        "job_catalog", "job_match_subscription", "job_favorite", "order_record",
        "user_vip", "download_file", "job_cache", "template_table",
        "application_tracker", "resume_evidence", "user_draft", "users",
    ):
        op.drop_table(table)
